## Resume-screening Model

### Life Cycle of a Machine Learning Project

- Uderstanding of the Problem Statement
- Data Collection
- Data checks to perform
- Exploratory data analysis
- Data pre-processing
- Model training
- Choose the best model

#### 1) Problem Statement
- This project will look into the applicants' resume and understands whether the applicant is fit for the role (Best Match) based on other variables such as Job Applicant Name, Age, Gender, Race, Ethnicity, Resume, Job Roles, Job Description


#### 2) Data Collection
- Dataset Source: https://www.kaggle.com/datasets/surendra365/recruitement-dataset/data
- The data consists of 9 columns and 10000 rows

### 2.1 Import Data and Required Packages
#### Importing Pandas, NumPy, Matplotlib, Seaborn and Warnings Library

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#### Import the CSV Data as Pandas DataFrame

In [4]:
df = pd.read_csv('data/job_applicant_dataset.csv')

#### Show Top 5 Records

In [5]:
df.head()

,Job Applicant Name,Age,Gender,Race,Ethnicity,Resume,Job Roles,Job Description,Best Match
0,Daisuke Mori,29,Male,Mongoloid/Asian,Vietnamese,"Proficient in Injury Prevention, Motivation, N...",Fitness Coach,A Fitness Coach is responsible for helping cl...,0
1,Taichi Shimizu,31,Male,Mongoloid/Asian,Filipino,"Proficient in Healthcare, Pharmacology, Medica...",Physician,"Diagnose and treat illnesses, prescribe medica...",0
2,Sarah Martin,46,Female,White/Caucasian,Dutch,"Proficient in Forecasting, Financial Modelling...",Financial Analyst,"As a Financial Analyst, you will be responsibl...",0
3,Keith Hughes,43,Male,Negroid/Black,Caribbean,"Proficient in Budgeting, Supply Chain Optimiza...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1
4,James Davis,49,Male,White/Caucasian,English,"Proficient in Logistics, Negotiation, Procurem...",Supply Chain Manager,A Supply Chain Manager oversees the entire sup...,1

Shape of the dataset

In [7]:
df.shape

(10000, 9)

### 2.2 Dataset Information
- Job Applicant Name: name of the applicant
- Age: Age of the applicant
- Gender: Sex of the applicant -> (Male/Female)
- Race: Applicant's Race -> (Mongoloid/Asian, White/Caucasian, Negroid/Black, etc.)
- Ethnicity: Applicant's Ethnicity -> (Vietnamese, Filipino, Dutch, etc.)
- Resume: Applicant's Resume
- Job Roles: Job listing
- Job Description: The description of the job
- Best Match: is the applicant fit for the role

### 3. Data checks to perform
- Check missing values
- Check duplicates
- Check data type
- Check the number of unique values of each column
- Check statistics of dataset
- Check various categories present in the different categorical column

#### 3.1 Check Missing Values

In [8]:
df.isna().sum()

Job Applicant Name    0
Age                   0
Gender                0
Race                  0
Ethnicity             0
Resume                0
Job Roles             0
Job Description       0
Best Match            0
dtype: int64

Insights: There are no missing values in the dataset

#### 3.2 Check Duplicates

In [9]:
df.duplicated().sum()

np.int64(0)

Insights: There are not duplicate values in the dataset

#### 3.3 Check Data Type

In [11]:
df.dtypes

Job Applicant Name      str
Age                   int64
Gender                  str
Race                    str
Ethnicity               str
Resume                  str
Job Roles               str
Job Description         str
Best Match            int64
dtype: object

#### 3.4 Check the number of unique values of each columns

In [12]:
df.nunique()

Job Applicant Name     547
Age                     31
Gender                   2
Race                     3
Ethnicity               21
Resume                9996
Job Roles               51
Job Description         51
Best Match               2
dtype: int64

#### 3.5 Check statistics of dataset

In [13]:
df.describe()

                Age  Best Match
count  10000.000000  10000.0000
mean      40.045200      0.4850
std        8.950909      0.4998
min       25.000000      0.0000
25%       32.000000      0.0000
50%       40.000000      0.0000
75%       48.000000      1.0000
max       55.000000      1.0000

Insights: There is no correlation between Age and Best Match

#### 3.6  Exploring Data

In [15]:
# define numerical & categorical columns
numeric_features = df.select_dtypes(include=np.number).columns.tolist()
categorical_features = df.select_dtypes(exclude=np.number).columns.tolist()

# print columns
print('We have {} numerical features: {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features: {}'.format(len(categorical_features), categorical_features))

We have 2 numerical features: ['Age', 'Best Match']

We have 7 categorical features: ['Job Applicant Name', 'Gender', 'Race', 'Ethnicity', 'Resume', 'Job Roles', 'Job Description']